import {
  splitBountyToRoleCoins,
  type IAcceptanceRecordRow,
  type IPrdRow,
  type IRequirementRow,
  type ISpecRow,
} from './rd.service';

const seedReq = (r: Omit<IRequirementRow, 'pmCoins' | 'tmCoins' | 'taskAcceptances'>): IRequirementRow => {
  const { pmCoins, tmCoins } = splitBountyToRoleCoins(r.bountyPoints);
  return { ...r, pmCoins, tmCoins, taskAcceptances: [] };
};

export const SEED_REQUIREMENTS: IRequirementRow[] = [
  seedReq({
    id: 'REQ-001',
    title: '用户登录模块优化',
    description: '优化现有登录流程，支持多端登录和单点登录',
    product: '核心平台',
    bountyPoints: 50,
    priority: 'P0',
    expectedDate: '2026-04-15',
    status: 'ai_developing',
    submitter: '张三',
    pm: '李四',
    tm: '王五',
    createdAt: '2026-04-01T00:00:00.000Z',
    updatedAt: '2026-04-05T00:00:00.000Z',
  }),
  seedReq({
    id: 'REQ-002',
    title: '数据报表导出功能',
    description: '支持将业务数据导出为Excel和PDF格式',
    product: '数据中台',
    bountyPoints: 20,
    priority: 'P1',
    expectedDate: '2026-04-20',
    status: 'spec_defining',
    submitter: '赵六',
    pm: '李四',
    tm: '王五',
    createdAt: '2026-04-02T00:00:00.000Z',
    updatedAt: '2026-04-04T00:00:00.000Z',
  }),
  seedReq({
    id: 'REQ-003',
    title: '消息推送系统升级',
    description: '集成飞书消息推送，支持多种消息模板',
    product: '消息服务',
    bountyPoints: 0,
    priority: 'P2',
    expectedDate: '2026-05-01',
    status: 'prd_writing',
    submitter: '钱七',
    pm: '李四',
    createdAt: '2026-04-03T00:00:00.000Z',
    updatedAt: '2026-04-03T00:00:00.000Z',
  }),
  seedReq({
    id: 'REQ-004',
    title: '移动端适配优化',
    description: '优化移动端页面响应式布局',
    product: '移动应用',
    bountyPoints: 30,
    priority: 'P1',
    expectedDate: '2026-04-25',
    status: 'pending_acceptance',
    submitter: '孙八',
    pm: '李四',
    tm: '王五',
    createdAt: '2026-03-28T00:00:00.000Z',
    updatedAt: '2026-04-06T00:00:00.000Z',
  }),
  seedReq({
    id: 'REQ-005',
    title: '新增客户管理模块',
    description: '支持客户信息的增删改查和批量导入',
    product: 'CRM',
    bountyPoints: 80,
    priority: 'P0',
    expectedDate: '2026-04-10',
    status: 'released',
    submitter: '周九',
    pm: '李四',
    tm: '王五',
    createdAt: '2026-03-20T00:00:00.000Z',
    updatedAt: '2026-04-08T00:00:00.000Z',
  }),
  seedReq({
    id: 'REQ-006',
    title: 'API性能监控',
    description: '增加API调用耗时监控和告警',
    product: '运维监控',
    bountyPoints: 10,
    priority: 'P2',
    expectedDate: '2026-05-10',
    status: 'backlog',
    submitter: '吴十',
    createdAt: '2026-04-07T00:00:00.000Z',
    updatedAt: '2026-04-07T00:00:00.000Z',
  }),
  seedReq({
    id: 'REQ-007',
    title: '权限管理重构',
    description: '基于RBAC模型的权限系统重构',
    product: '核心平台',
    bountyPoints: 100,
    priority: 'P0',
    expectedDate: '2026-04-30',
    status: 'ai_developing',
    submitter: '郑一',
    pm: '李四',
    tm: '王五',
    createdAt: '2026-03-25T00:00:00.000Z',
    updatedAt: '2026-04-06T00:00:00.000Z',
  }),
];

export const SEED_PRDS: IPrdRow[] = [
  {
    id: 'prd-001',
    requirementId: 'REQ-001',
    title: '用户认证系统PRD',
    background: '统一认证与多端登录',
    objectives: '提升登录成功率与安全性',
    featureList: [
      {
        id: 'f1',
        name: 'OAuth2 登录',
        description: '支持主流 IdP',
        acceptanceCriteria: ['支持飞书', '支持企业微信'],
      },
    ],
    nonFunctional: '可用性 99.9%',
    status: 'approved',
    version: 2,
    author: '张三',
    createdAt: '2026-01-10T00:00:00.000Z',
    updatedAt: '2026-01-15T00:00:00.000Z',
    reviews: [],
  },
  {
    id: 'prd-002',
    requirementId: 'REQ-002',
    title: '数据导出PRD',
    background: '多格式导出',
    objectives: '支持 Excel/PDF',
    featureList: [
      {
        id: 'f2',
        name: '导出任务',
        description: '异步导出大表',
        acceptanceCriteria: ['进度可查询'],
      },
    ],
    nonFunctional: '导出超时告警',
    status: 'reviewing',
    version: 1,
    author: '李四',
    createdAt: '2026-01-12T00:00:00.000Z',
    updatedAt: '2026-01-14T00:00:00.000Z',
    reviews: [],
  },
  {
    id: 'prd-003',
    requirementId: 'REQ-003',
    title: '消息推送PRD',
    background: '飞书模板消息',
    objectives: '可配置模板',
    featureList: [
      {
        id: 'f3',
        name: '模板管理',
        description: 'CRUD 模板',
        acceptanceCriteria: ['审核发布'],
      },
    ],
    nonFunctional: '限流与重试',
    status: 'draft',
    version: 1,
    author: '王五',
    createdAt: '2026-01-13T00:00:00.000Z',
    updatedAt: '2026-01-13T00:00:00.000Z',
    reviews: [],
  },
];

const apiSample = {
  path: '/api/v1/example',
  method: 'GET',
  description: '示例',
  requestParams: {},
  response: {},
};

export const SEED_SPECS: ISpecRow[] = [
  {
    id: 'spec-001',
    prdId: 'prd-001',
    fsMarkdown: '# FS\n',
    tsMarkdown: '# TS\n',
    functionalSpec: {
      apis: Array.from({ length: 8 }, (_, i) => ({ ...apiSample, path: `/api/fs/${i}` })),
      uiComponents: Array.from({ length: 12 }, (_, i) => ({
        name: `UI${i}`,
        type: 'div',
        props: {},
        events: [],
      })),
      interactions: Array.from({ length: 6 }, (_, i) => ({
        trigger: `t${i}`,
        action: `a${i}`,
      })),
    },
    technicalSpec: {
      databaseSchema: { tables: ['users'] },
      architecture: '微服务',
      thirdPartyIntegrations: ['a', 'b', 'c'],
    },
    machineReadableJson: '{}',
    status: 'reviewing',
    createdAt: '2026-01-15T00:00:00.000Z',
    updatedAt: '2026-01-15T10:30:00.000Z',
    reviews: [],
  },
  {
    id: 'spec-002',
    prdId: 'prd-002',
    functionalSpec: {
      apis: Array.from({ length: 4 }, (_, i) => ({ ...apiSample, path: `/api/s2/${i}` })),
      uiComponents: Array.from({ length: 6 }, (_, i) => ({
        name: `U2-${i}`,
        type: 'div',
        props: {},
        events: [],
      })),
      interactions: Array.from({ length: 3 }, (_, i) => ({
        trigger: `t2-${i}`,
        action: `a2-${i}`,
      })),
    },
    technicalSpec: {
      databaseSchema: {},
      architecture: '',
      thirdPartyIntegrations: ['x', 'y'],
    },
    machineReadableJson: '',
    status: 'draft',
    createdAt: '2026-01-14T00:00:00.000Z',
    updatedAt: '2026-01-14T16:45:00.000Z',
    reviews: [],
  },
  {
    id: 'spec-003',
    prdId: 'prd-003',
    functionalSpec: {
      apis: [
        { ...apiSample, path: '/api/m/a' },
        { ...apiSample, path: '/api/m/b' },
      ],
      uiComponents: Array.from({ length: 20 }, (_, i) => ({
        name: `M${i}`,
        type: 'div',
        props: {},
        events: [],
      })),
      interactions: Array.from({ length: 8 }, (_, i) => ({
        trigger: `m${i}`,
        action: `n${i}`,
      })),
    },
    technicalSpec: {
      databaseSchema: { ok: true },
      architecture: '单体',
      thirdPartyIntegrations: ['z'],
    },
    machineReadableJson: '{"version":1}',
    status: 'approved',
    createdAt: '2026-01-13T00:00:00.000Z',
    updatedAt: '2026-01-13T09:20:00.000Z',
    reviews: [],
  },
];

/** 与客户端 createDefaultOrgSpecConfig 对齐的精简默认配置 */
export const SEED_ORG_SPEC_CONFIG = {
  id: 'org-spec-default',
  orgName: '默认组织',
  version: 1,
  defaultLanguage: 'typescript',
  updatedAt: new Date().toISOString(),
  languages: {
    java: {
      language: 'java',
      displayName: 'Java',
      enabled: true,
      styleGuide: ['遵循 Google Java Style'],
      mustFollow: ['分层架构'],
      forbidden: ['禁止吞异常'],
      toolchain: ['JDK 21'],
      testing: ['JUnit'],
    },
    python: {
      language: 'python',
      displayName: 'Python',
      enabled: true,
      styleGuide: ['PEP8'],
      mustFollow: ['类型注解'],
      forbidden: ['裸 except'],
      toolchain: ['Python 3.11+'],
      testing: ['pytest'],
    },
    go: {
      language: 'go',
      displayName: 'Go',
      enabled: true,
      styleGuide: ['gofmt'],
      mustFollow: ['context 透传'],
      forbidden: ['panic 业务错误'],
      toolchain: ['Go 1.22+'],
      testing: ['table-driven'],
    },
    node: {
      language: 'node',
      displayName: 'Node.js',
      enabled: true,
      styleGuide: ['ESLint'],
      mustFollow: ['参数校验'],
      forbidden: ['未处理 Promise'],
      toolchain: ['Node.js 20+'],
      testing: ['单测'],
    },
    react: {
      language: 'react',
      displayName: 'React',
      enabled: true,
      styleGuide: ['函数组件'],
      mustFollow: ['hooks 规范'],
      forbidden: ['渲染副作用'],
      toolchain: ['React 19'],
      testing: ['RTL'],
    },
    vue: {
      language: 'vue',
      displayName: 'Vue',
      enabled: true,
      styleGuide: ['Composition API'],
      mustFollow: ['Pinia'],
      forbidden: ['模板复杂表达式'],
      toolchain: ['Vue 3'],
      testing: ['组件单测'],
    },
    typescript: {
      language: 'typescript',
      displayName: 'TypeScript',
      enabled: true,
      styleGuide: ['strict'],
      mustFollow: ['DTO 分离'],
      forbidden: ['滥用断言'],
      toolchain: ['TS 5+'],
      testing: ['核心逻辑单测'],
    },
  },
};

export const SEED_ACCEPTANCE: IAcceptanceRecordRow[] = [
  {
    id: 'acc-001',
    requirementId: 'REQ-004',
    reviewer: '张三',
    scores: { functionality: 4, valueMatch: 5, experience: 4 },
    feedback: '功能基本实现，但部分边界场景处理需要优化',
    result: 'approved',
    createdAt: '2026-01-18T00:00:00.000Z',
  },
];
